# http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: ./content/satis.json
    destination: /local/app/packages/
  - source: ./content/satis_build.sh
    destination: /local/app/
  - source: ./scripts/cd_utils.sh
    destination: /local/basefarm/
permissions:
  - object: /local/app/packages/
    pattern: "satis.json"
    owner: root
    group: root
    mode: 600
    type:
      - file
  - object: /local/basefarm
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
  - object: /local/app
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: ./scripts/webapp_stop.sh
      timeout: 300
      runas: root
    - location: ./scripts/webapp_prep.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./scripts/webapp_config.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/webapp_start.sh
      timeout: 300
      runas: root
